//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalyserBestPractis_Dynamics365.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class SettingsBP : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsBP defaultInstance = ((SettingsBP)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsBP())));
        
        public static SettingsBP Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[SPD][ObjectName]")]
        public string AxEnum {
            get {
                return ((string)(this["AxEnum"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[SPD][ObjectName]")]
        public string AxEdt {
            get {
                return ((string)(this["AxEdt"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ObjectName].[SPD]")]
        public string AxEdtExtension {
            get {
                return ((string)(this["AxEdtExtension"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ObjectName].[SPD]")]
        public string AxEnumExtension {
            get {
                return ((string)(this["AxEnumExtension"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[SPD][ObjectName]")]
        public string AxClass {
            get {
                return ((string)(this["AxClass"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ObjectName].[SPD]")]
        public string AxFormExtension {
            get {
                return ((string)(this["AxFormExtension"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[SPD][ObjectName]")]
        public string AxLabelFile {
            get {
                return ((string)(this["AxLabelFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[SPD][ObjectName]")]
        public string AxMap {
            get {
                return ((string)(this["AxMap"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ObjectName].[SPD]")]
        public string AxMapExtension {
            get {
                return ((string)(this["AxMapExtension"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[SPD][ObjectName]")]
        public string AxMenu {
            get {
                return ((string)(this["AxMenu"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ObjectName].[SPD]")]
        public string AxMenuExtension {
            get {
                return ((string)(this["AxMenuExtension"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[SPD][ObjectName]")]
        public string AxMenuItemAction {
            get {
                return ((string)(this["AxMenuItemAction"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ObjectName].[SPD]")]
        public string AxMenuItemActionExtension {
            get {
                return ((string)(this["AxMenuItemActionExtension"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[SPD][ObjectName]")]
        public string AxMenuItemDisplay {
            get {
                return ((string)(this["AxMenuItemDisplay"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ObjectName].[SPD]")]
        public string AxMenuItemDisplayExtension {
            get {
                return ((string)(this["AxMenuItemDisplayExtension"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[SPD][ObjectName]")]
        public string AxMenuItemOutput {
            get {
                return ((string)(this["AxMenuItemOutput"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ObjectName].[SPD]")]
        public string AxMenuItemOutputExtension {
            get {
                return ((string)(this["AxMenuItemOutputExtension"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[SPD][ObjectName]")]
        public string AxPage {
            get {
                return ((string)(this["AxPage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[SPD][ObjectName]")]
        public string AxQuery {
            get {
                return ((string)(this["AxQuery"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[SPD][ObjectName]")]
        public string AxReport {
            get {
                return ((string)(this["AxReport"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[SPD][ObjectName]")]
        public string AxResource {
            get {
                return ((string)(this["AxResource"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[SPD][ObjectName]")]
        public string AxRuleSet {
            get {
                return ((string)(this["AxRuleSet"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[SPD][ObjectName]")]
        public string AxSecurityDuty {
            get {
                return ((string)(this["AxSecurityDuty"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[SPD][ObjectName]")]
        public string AxSecurityPolicy {
            get {
                return ((string)(this["AxSecurityPolicy"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[SPD][ObjectName]")]
        public string AxSecurityPrivilege {
            get {
                return ((string)(this["AxSecurityPrivilege"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[SPD][ObjectName]")]
        public string AxSecurityRole {
            get {
                return ((string)(this["AxSecurityRole"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[SPD][ObjectName]")]
        public string AxService {
            get {
                return ((string)(this["AxService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[SPD][ObjectName]")]
        public string AxTable {
            get {
                return ((string)(this["AxTable"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[SPD][ObjectName]")]
        public string AxTile {
            get {
                return ((string)(this["AxTile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[SPD][ObjectName]")]
        public string AxView {
            get {
                return ((string)(this["AxView"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ObjectName].[SPD]")]
        public string AxViewExtension {
            get {
                return ((string)(this["AxViewExtension"]));
            }
        }
    }
}
